### ISSUE TITLE
Enable / Disable Indication

### ISSUE THREAD

**Issue by ciribob** [ciribob/DCS-SimpleRadio#6]
Make the Radio Menu indicate clearly if DCS SR is enabled or disabled

**Comment by ciribob** [comment]
or have a separate enable / disable button

**Comment by splash99** [comment]
I made a new version with separate menu entries for enable/disable, mute/unmute on outsiders and CA On/Off. Your code is very readable and it was easy. I can send it to you.

**Comment by ciribob** [comment]
Thanks Splash! Yes send it over, thats great. If you use GitHub, send as a pull request

**Comment by splash99** [comment]
Hi, excuse me but I don't know how to add files to github. Please find in
the link below a zip with some minor modifications:

New menus for Plugin ON/OFF, Mute outsiders ON/OFF, CA On/Off. As requested
by Tarres, plugin is OFF, mute outsiders is ON and CA is ON by default, but
I suppose that can like or dislike to some users.

https://www.dropbox.com/s/ngfv2b7jbn2i3tw/DCS-SimpleRadio-1.3.0%20modified.zip?dl=0

I'm thinking in a solution to establish limits in FC3 radios and I hope to
send it to you this weekend. Some pilots from my squadron are asked to
modify GUI in order to work in this way (for example):

224.000 MHz

if you press below "4" it will advance to 225.000, if you press again it
will be 226.000, etc.  but if you have 229.000 and press below "9" they
want to change to 220.000 (currently changes to 230.000). I'm not sure, but
probably I'll made the modification in GUI.

Thanks for your job.

2016-03-18 14:18 GMT+01:00 Ciaran Fisher notifications@github.com:

**Comment by splash99** [comment]
What a surprise! I replied at your email and I found it published here.

**Comment by ciribob** [comment]
Ah yes, GitHub does that automatically :)

**Comment by ciribob** [comment]
Fixed in #11
